# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'IntellarcSocial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntellarcSocial
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SwiftLint'
	pod 'FBSDKLoginKit'

  target 'IntellarcSocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntellarcSocialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
